set shell := ["zsh", "-c"]

# 默认动作：列出所有命令
default:
    @just --list

# 编译 (Release)
build:
    cargo build --release

# 运行
run:
    cargo run

# 代码检查 (Clippy + Format)
check:
    cargo fmt -- --check
    cargo clippy -- -D warnings

# 本地测试
test:
    cargo test
    
# 更新环境 (Devbox + Cargo)
update:
    devbox update
    cargo update