# === user env核心 ===
brew "gh"
brew "just"
brew "nushell"
brew "mise"
brew "chezmoi"

# === CLI 增强 ===
brew "starship"
brew "carapace"
brew "fd"
brew "ripgrep"
brew "dust"
brew "tealdeer"
brew "gtrash"
brew "jq"
brew "gum"

# === ai+TUI 工作流 ===
brew "yazi"
brew "zellij"
brew "helix"
brew "lazygit"
brew "onefetch"
brew "scc"
brew "gemini-cli"
brew "distrobox"
brew "btop"
brew "podman-tui"

# === Git ===
brew "git-delta"
# brew "lefthook"
# brew "gitleaks"
brew "git-lfs"

# ===== Monitor =====
#brew "watchexec"
#brew "lnav"
brew "tailspin"
brew "viddy"
#brew "angle-grinder"

# ===== Containers =====
brew "docker-compose"
# brew "dive"
# brew "hadolint"
# brew "syft"
# brew "k9s"

# 网络
brew "curlie"               # curl 封装 (像 httpie)
brew "mosh"
# brew "doggo"
# brew "trippy"
# brew "croc"
# brew "miniserve"
# brew "websocat"
# brew "zrok"

# 测试与性能
# brew "fio"
# brew "oha"
# brew "ffuf"   
# brew "hyperfine"

# 数据库
# brew "sqlfluff"
# brew "gobackup"
# brew "usql"

# === Security ===
# brew "trivy"
# brew "rustscan"
# brew "lynis"

# ===== Docs =====
# brew "pandoc"

# =====yazi预览 =====
brew "ffmpegthumbnailer"
brew "p7zip"
brew "poppler"
brew "chafa"
brew "glow"
# brew "bat"